### ISSUE TITLE
Install error with "permission denny"!

### ISSUE THREAD

**Issue by IcemanJia** [cui-xiaoang96/Install_SeismicUnix-SU-#1]
Nothing!

**Comment by cui-xiaoang96** [comment]
FUCK U!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月1日(星期三) 晚上9:32
收件人:&nbsp;"cui-xiaoang96/Install_SeismicUnix-SU-"<Install_SeismicUnix-SU-@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[cui-xiaoang96/Install_SeismicUnix-SU-] Install error with "permission deny"! (#1)





 
Suck my dick
